#!/usr/bin/env perl

use strict;
use warnings;
use Term::ANSIColor;
use Cwd qw( getcwd );

$| = 1;

# my $npm = `sh -c 'command -v pnpm'` ? "pnpm" : "yarn";
my $npm = -f "pnpm-lock.yaml" ? "pnpm" : -f "yarn.lock" ? "yarn" : "npm";

my @SERVERS = (
    # Name ,   Command     , File/Directory
    ['ReactNative', "$npm run start", 'expo-env.d.ts'],
    ['Angular', "$npm start", 'node_modules/@angular'],
    ['Vite', "$npm dev", 'node_modules/vite'],
    ['Svelte', "$npm dev", 'node_modules/svelte'],
    ['Nestjs', "$npm run start:dev", 'node_modules/@nestjs'],
    ['Django', 'python3 manage.py runserver', 'manage.py'],
    ['Rails', 'bin/rails server', 'bin/rails'],
    ['Nextjs', "$npm run dev", 'node_modules/next'],
    ['React', "$npm start", 'node_modules/react'],
    ['Nodejs', "$npm start", 'node_modules/express'],
    );

sub error_exit {
    print colored("Could not determine the runserver command for project"
                  , "red") . "\n";
    exit(1);
}

sub main {
    foreach my $server (@SERVERS) {
        my ($name, $cmd, $file) = @$server;
        next unless (-d $file || -f $file);
        my $dir = getcwd();
        print colored("Running $name server ...\n", "green");
        system("st -e bash -c 'cd $dir && $cmd' &");
        # system($cmd);
        exit;
    }
    error_exit();
}

main();
